services:
  db:
    image: mysql:latest
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1']
    environment:
      MYSQL_DATABASE: 'storage'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'storage'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'storage'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=8G
      - MAX_EXECUTION_TIME=3600000
      - PHP_MEMORY_LIMIT=8G
      - MEMORY_LIMIT=8G
    depends_on:
      - db

volumes:
  my-db:
